# Generated by Django 2.2 on 2021-06-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_auto_20210612_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='myprojects/static/img'),
        ),
    ]
