# Generated by Django 2.2 on 2021-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_auto_20210617_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(match='foo.*', path='static/img', recursive=True),
        ),
    ]
