# Generated by Django 2.2 on 2021-06-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0007_auto_20210617_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
