# Generated by Django 2.2 on 2021-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0011_auto_20210618_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
